name = "ResEE"
uuid = "539b6a15-2144-4f08-8574-27224deb4b81"
authors = ["Zhiyuan Yao and Yu Li"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
LinearAlgebra = ">=1.8"
OffsetArrays = ">=1.8"
SparseArrays = ">=1.8"
julia = ">=1.6"
